threshold_ms: 1000
webhook_url: https://discord.com/api/webhooks/1510050246791528560/CRRTR2WcN1yocsatMqHmBFmxr_w0S6Ru6MiI_ERkGnEqiCRK7A0j_5m27EtFh6t9-ulj
urls:
  - name: GitHub API
    url: https://api.github.com/zen
    interval: 60
    expected_status: 200

  - name: Google
    url: https://www.google.com
    interval: 60
    expected_status: 200

  - name: My FastAPI App
    url: http://localhost:8000
    interval: 30
    expected_status: 200